/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;

/**
 *
 * @author hanzor
 */
public class Gifs extends javax.swing.JFrame {

    /**
     * Creates new form x
     */
    public Gifs() {
        initComponents();
        this.dmg.setIcon(new ImageIcon("imagenes/dmg--.jpg"));
        this.dmg.setVisible(false);
        this.dmgT.setIcon(new ImageIcon("imagenes/dmgT++.jpg"));
        this.dmgT.setVisible(false);
        this.hp.setIcon(new ImageIcon("imagenes/hp++.jpg"));
        this.hp.setVisible(false);
        this.def.setIcon(new ImageIcon("imagenes/def++.jpg"));
        this.def.setVisible(false);
        this.panel.setBackground(new Color(0,0,0,0));
        this.accion.setBackground(new Color(0,0,0,0));
        this.accion.setBorder(null);
        this.jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        this.jScrollPane1.setViewportBorder(null);
        this.jScrollPane1.setBorder(null);
        this.jScrollPane1.setBackground(new Color(0,0,0,0));
        setLocationRelativeTo(null);
        setTitle("!!! DIALOGO DE COMBATE !!!");
        setIconImage(new ImageIcon("imagenes/icon.png").getImage());
        this.vida.setBackground(Color.DARK_GRAY);
        this.vida.setStringPainted(true);
        this.vida.setVisible(false);
        this.vida.setForeground(Color.red);
        this.estamina.setBackground(Color.DARK_GRAY);
        this.estamina.setVisible(false);
        this.estamina.setStringPainted(true);
        this.estamina.setForeground(Color.green);
        this.entorno.setIcon(new ImageIcon("imagenes/entorno.jpg"));
        this.entorno.setMaximumSize(new Dimension(300, 400));
        this.entorno.setSize(new Dimension(300, 400));
        pack();
    }
    
    public void setFondo(String image){
        try{
            this.fondo.setIcon(new ImageIcon("imagenes/"+image));
            this.fondo.setMaximumSize(new Dimension(300, 400));
            if(image.equalsIgnoreCase("jugador.gif"))
                this.estamina.setVisible(true);
        }catch(Exception e){
            throw e;
        }
    }
    
    public void setMensaje(String A, String B,String C,boolean dark) throws Exception{
        try{
            if(dark){
                this.preparate.setForeground(Color.black);
                this.morir.setForeground(Color.black);
                this.vida.setVisible(true);
            }
            

            String preparate = A;
            String morir = B;
            String accion = C;
            
            for(int i = 0; i < preparate.length();i++){
                this.preparate.setText(preparate.substring(0, i+1));
                Thread.sleep(100);
            }
            
            for(int i = 0; i < morir.length();i++){
                this.morir.setText(morir.substring(0, i+1));
                Thread.sleep(100);
            }
            
            if(accion.equals("DERROTA")){
                this.accion.setForeground(Color.red);
            }else if(accion.equals("VICTORIA")){
                this.accion.setForeground(Color.green);
            }
            
            
            for(int i = 0; i < accion.length();i++){
                this.accion.setText(accion.substring(0, i+1));
                Thread.sleep(70);
            }
            
            
            
            Thread.sleep(dark ? 3000 : 1500);
            if(accion.contains("DERROTA")){
                Thread.sleep(1500);
            }else if(accion.contains("VICTORIA")){
                Thread.sleep(1500);
            }
            setVisible(false);
        }catch(Exception e){
            throw e;
        }
    }
    
    public void setEntidad(Entidad e) throws Exception{
        this.vida.setMaximum((int) e.getMaximo());
        this.vida.setValue((int) e.getVida());
        this.estamina.setMaximum(3);
        this.estamina.setValue(e.getEstamina());
           
    }
    
    public void nombre(String s){
        if(s.contains("dmgT++"))
            this.dmgT.setVisible(true);
        if(s.contains("hp++"))
            this.hp.setVisible(true);
        if(s.contains("def++"))
            this.def.setVisible(true);
        if(s.contains("dmg--"))
            this.dmg.setVisible(true);
        
        if(!s.equals("Jugador")) 
            this.nombre.setText(s.split(" ")[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accion = new javax.swing.JTextArea();
        dmg = new javax.swing.JLabel();
        hp = new javax.swing.JLabel();
        def = new javax.swing.JLabel();
        dmgT = new javax.swing.JLabel();
        preparate = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        vida = new javax.swing.JProgressBar();
        morir = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        estamina = new javax.swing.JProgressBar();
        entorno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBorder(null);
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accion.setEditable(false);
        accion.setColumns(20);
        accion.setFont(new java.awt.Font("Yrsa SemiBold", 1, 20)); // NOI18N
        accion.setForeground(java.awt.Color.white);
        accion.setLineWrap(true);
        accion.setRows(5);
        jScrollPane1.setViewportView(accion);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 50));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 400, 50));
        getContentPane().add(dmg, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 40, 30));
        getContentPane().add(hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 40, 30));
        getContentPane().add(def, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 40, 30));
        getContentPane().add(dmgT, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 40, 30));

        preparate.setFont(new java.awt.Font("Yrsa SemiBold", 1, 24)); // NOI18N
        preparate.setForeground(java.awt.Color.white);
        getContentPane().add(preparate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 140, 30));

        nombre.setFont(new java.awt.Font("Yrsa SemiBold", 1, 32)); // NOI18N
        nombre.setForeground(java.awt.Color.white);
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, 50));

        vida.setBackground(java.awt.Color.black);
        vida.setFont(new java.awt.Font("Yrsa SemiBold", 1, 15)); // NOI18N
        vida.setForeground(java.awt.Color.white);
        vida.setValue(100);
        vida.setStringPainted(true);
        getContentPane().add(vida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 20));

        morir.setFont(new java.awt.Font("Yrsa SemiBold", 1, 24)); // NOI18N
        morir.setForeground(java.awt.Color.white);
        getContentPane().add(morir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, 50));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        estamina.setBackground(java.awt.Color.black);
        estamina.setFont(new java.awt.Font("Yrsa SemiBold", 1, 15)); // NOI18N
        estamina.setForeground(java.awt.Color.white);
        estamina.setMaximum(3);
        estamina.setToolTipText("");
        estamina.setValue(100);
        estamina.setStringPainted(true);
        getContentPane().add(estamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, 20));
        getContentPane().add(entorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -2, 400, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gifs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gifs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gifs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gifs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gifs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea accion;
    private javax.swing.JLabel def;
    private javax.swing.JLabel dmg;
    private javax.swing.JLabel dmgT;
    private javax.swing.JLabel entorno;
    private javax.swing.JProgressBar estamina;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel hp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel morir;
    private javax.swing.JLabel nombre;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel preparate;
    private javax.swing.JProgressBar vida;
    // End of variables declaration//GEN-END:variables
}
