/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

/**
 *
 * @author hanzor
 */
public class Resultado extends javax.swing.JFrame {

    /**
     * Creates new form Resultado
     */
    public Resultado() {
        initComponents();
        setLocationRelativeTo(null);
        this.historia.setOpaque(false);
        this.historia.setEditable(false);
        this.historia.setBackground(new Color(255,255,255,0));
        this.historia.setBorder(null);
        this.historia.setContentType("text/html");
        this.historia.setAlignmentX(Component.CENTER_ALIGNMENT);
        this.jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        this.jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        this.jScrollPane1.setViewportBorder(null);
        this.jScrollPane1.setBorder(null);
        this.jScrollPane1.setOpaque(false);
        this.jScrollPane1.setBackground(new Color(255,255,255,0));
        this.jScrollPane1.getViewport().setBackground(new Color(0, 0, 0, 0));
        this.jScrollPane1.getViewport().setOpaque(false);
        this.jScrollPane1.setViewportBorder(BorderFactory.createEmptyBorder());
        this.jScrollPane1.setOpaque(false);
        this.jScrollPane1.setBackground(new Color(0, 0, 0, 0));
        this.jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        HTMLEditorKit kit = new HTMLEditorKit();
        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule("html,p {background: rgba(0,0,0,0);text-align:center;font-size:50px;}");
        styleSheet.addRule("font {font-size: 16px;text-align:center;}");
        historia.setEditorKit(kit);
        this.jPanel1.setBackground(new Color(255,255,255,0));
        this.jPanel1.setOpaque(false);
    }
    
    public void setFondo(String image, boolean victoria){
        this.setLayout(null);
        this.setSize(710, 370);
        this.setTitle("EL FIN");
        this.setPreferredSize(new Dimension(710, 370));
        this.entorno.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("imagenes/"+image+".gif")).getImage().getScaledInstance(710, 370, Image.SCALE_DEFAULT)));
        this.entorno.setBounds(0, 0, 710, 370);
        this.entorno.setPreferredSize(new Dimension(710, 370));
        this.entorno.repaint();
        setIconImage(new ImageIcon(getClass().getResource("imagenes/icon.png")).getImage());
        this.setVisible(true);
        try {
            if(victoria){
                this.tumba.setVisible(false);
                this.jPanel1.setBounds(jPanel1.getX() + 130, jPanel1.getY()- 20, jPanel1.getWidth(), jPanel1.getHeight());
                this.jPanel1.repaint();
                historia("Has ganado.<br>Por ahora...", 60, 8000);
            }else{
                this.jPanel1.setBounds(jPanel1.getX(), jPanel1.getY() + 40, jPanel1.getWidth(), jPanel1.getHeight());
                this.jPanel1.repaint();
                historia("Tras una intensa batalla contra la tribu oscura...", 60, 2000);
                historia("Nuestro héroe ha sucumbido ante la oscuridad...", 60, 3000);
                historia("Lo que parecía ser un rayo de luz", 60, 3000);
                historia("Ahora no es más que un anhelo distante...", 60, 3000);
                historia("Poco a poco lo que queda de la humanidad es masacrado por el mal...", 60, 3000);
                historia("Ya no hay nada que pueda evitarlo...", 60, 3000);
                historia("FIN DE LA PARTIDA.<br>HAS MUERTO.", 60, 3000);              
            }
        } catch (Exception e) {

        }

        this.revalidate();
        this.validate();
        this.pack();
        this.repaint();
        
    }
    
    public void historia(String historia, int a, int b) throws InterruptedException{
        String f = jScrollPane1.getFont().getFamily();
        for(int i = 0; i < historia.length();i++){
            this.historia.setText("<html><p><b><font face=\""+f+"\" color=\"white\">" +historia.substring(0, i+1)+"</font></b></p></html>");
            this.historia.repaint();
            Thread.sleep(a);
        }
        Thread.sleep(b);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tumba = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historia = new javax.swing.JEditorPane();
        entorno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tumba.setIcon(new ImageIcon(new ImageIcon("imagenes/tumba.gif").getImage().getScaledInstance(110, 120, Image.SCALE_DEFAULT)));
        getContentPane().add(tumba, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 110, 120));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        historia.setFont(new java.awt.Font("Yrsa SemiBold", 1, 19)); // NOI18N
        jScrollPane1.setViewportView(historia);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 490, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 650, 130));
        getContentPane().add(entorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultado();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel entorno;
    private javax.swing.JEditorPane historia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tumba;
    // End of variables declaration//GEN-END:variables
}
